//LOCALHOST DEPLOY
//-----------------

// -------------------------GET ROUTES-----------------------
### GET ALL CONTACTS
GET http://localhost:8080/travel HTTP/1.1
### GET CONTACT BY ID
GET http://localhost:8080/travel/641cb7213dd722d614c6d6e3 HTTP/1.1


// ---------------ASIA COLLECTION-------------------

### GET PLACE TO TRAVEL BY ID 
GET http://localhost:8080/travel/asia/641ce67999cad3981cbf0c34 HTTP/1.1


// -------------AMERICA COLLECTION----------------

### GET PLACE TO TRAVEL BY ID
GET http://localhost:8080/travel/america/641ceb4399cad3981cbf0c39 HTTP/1.1

// --------------AFRICA COLLECTION -------------------



// --------------EUROPE COLLECTION ------------------

### GET PLACE TO TRAVEL BY ID

GET http://localhost:8080/travel/europe/641d0b5799cad3981cbf0c41 HTTP/1.1


// --------------OCEANIA COLLECTION-------------------

### GET PLACE TO TRAVEL BY ID
GET http://localhost:8080/travel/oceania/641d0f7399cad3981cbf0c43 HTTP/1.1