//LOCALHOST DEPLOY
//-----------------

// -------------------------GET ROUTES-----------------------
### GET ALL PLACES
GET http://localhost:8080/travel HTTP/1.1
### GET PLACE BY ID
GET http://localhost:8080/travel/641cbc723dd722d614f803a3 HTTP/1.1


// ---------------ASIA COLLECTION-------------------

### GET PLACE TO TRAVEL BY ID 
GET http://localhost:8080/travel/asia/641ce67999cad3981cbf0c34 HTTP/1.1


// -------------AMERICA COLLECTION----------------

### GET PLACE TO TRAVEL BY ID
GET http://localhost:8080/travel/america/641ceb4399cad3981cbf0c39 HTTP/1.1

// --------------AFRICA COLLECTION -------------------

### GET PLACE TO TRAVEL BY ID
GET http://localhost:8080/travel/africa/641d10ee99cad3981cbf0c45 HTTP/1.1
// --------------EUROPE COLLECTION ------------------

### GET PLACE TO TRAVEL BY ID

GET http://localhost:8080/travel/europe/641d0b5799cad3981cbf0c41 HTTP/1.1


// --------------OCEANIA COLLECTION-------------------

### GET PLACE TO TRAVEL BY ID
GET http://localhost:8080/travel/oceania/641d0f7399cad3981cbf0c43 HTTP/1.1

// -------------------------POST ROUTES-----------------------

// ---------------ASIA COLLECTION-------------------

### CREATE TRAVEL PLACE ASIA
POST http://localhost:8080/travel/asia HTTP/1.1
content-type: application/json

{
    "place": "YAKISOBA",
    "continent": "Asia",
    "country": "Japan",
    "city": "Tokyo",
    "activities": "Eat",
    "admissionCost": "About $5",
    "bestDateToTravel": "Winter",
    "suggestion": ""
}

// -------------AMERICA COLLECTION----------------

### CREATE TRAVEL PLACE AMERICA
POST http://localhost:8080/travel/america HTTP/1.1
content-type: application/json

{
    "place": "MASP",
    "continent": "America",
    "country": "Brasil",
    "city": "São Paulo",
    "activities": "Observe and admire art",
    "admissionCost": "The cost depends on the day but the medium ticket it is like $2",
    "bestDateToTravel": "March to August",
    "suggestion": ""
}

// --------------EUROPE COLLECTION ------------------

### CREATE TRAVEL PLACE EUROPE
POST http://localhost:8080/travel/europe HTTP/1.1
content-type: application/json

{
    "place": "Eiffel Tower",
    "continent": "Europe",
    "country": "France",
    "city": "Paris",
    "activities": "Observe and admire art",
    "admissionCost": "The cost depends on the day but the medium ticket it is like $50",
    "bestDateToTravel": "March to August",
    "suggestion": ""
}

// --------------AFRICA COLLECTION -------------------

### CREATE TRAVEL PLACE AFRICA
POST http://localhost:8080/travel/africa HTTP/1.1
content-type: application/json

{
    "place": "Zoo",
    "continent": "Africa",
    "country": "South Africa",
    "city": "Namimbi",
    "activities": "Observe and admire the animals",
    "admissionCost": "The cost depends on the day but the medium ticket it is like $5",
    "bestDateToTravel": "March to August",
    "suggestion": ""
}

// --------------OCEANIA COLLECTION-------------------

### CREATE TRAVEL PLACE OCEANIA
POST http://localhost:8080/travel/oceania HTTP/1.1
content-type: application/json

{
    "place": "Kangoroo",
    "continent": "Oceania",
    "country": "Australia",
    "city": "Sidney",
    "activities": "Observe and admire the animals",
    "admissionCost": "The cost depends on the day but the medium ticket it is like $5",
    "bestDateToTravel": "March to August",
    "suggestion": ""
}

